  - uses: Platane/snk@v3
    with:
      github_user_name: heba-abdelwahab25
      outputs: |
        dist/github-contribution-grid-snake.svg

  - uses: peaceiris/actions-gh-pages@v4
    with:
      github_token: ${{ secrets.GITHUB_TOKEN }}
      publish_dir: dist
      publish_branch: output
